apiVersion: v1
kind: Service
metadata:
  name: hsc-result-admin-client-service
spec:
  type: ClusterIP
  selector:
    app: hsc-result-admin-client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5173

